### PR TITLE
add project configration inheritance support

### PR DESCRIPTION
**Pull request by Jnoack331**
This would help with configuration managment because you can extend another `.shopware-project.yml` file to reuse or override configurations. This is useful when you have multiple projects with the same configuration. You can also use this to create a base configuration for your stages or teams and extend it for your own needs.
This also can be used to toggle specific plugin configurations for different stages e.g. enabling/disabling the Paypal sandbox mode depending on the environment.

### CODE REVIEW

**Comment by shyim** [comment]
What do you think about naming it `include` and allow to be an array of files? In that way we would support multiple files.

Little bit like docker compose https://docs.docker.com/compose/multiple-compose-files/include/

**Comment by Jnoack331** [comment]
@shyim sure, i guess the priority would be set by the order of the files provided?

**Comment by shyim** [comment]
yes :)

**Comment by Jnoack331** [comment]
@shyim Just looked a bit into the docker documentation. That include change would reverse the override logic correct? Would that mean an include could override a value in the current configuration, or is this handled differently in docker compose?

**Comment by Jnoack331** [comment]
@shyim I changed it so its now using the `include` statement with multiple files to include. I didnt change the base merge logic so that values from the main file always have priority, this is propably the most intuitive.

**Comment by shyim** [comment]
Thank you!

**Pull request merged**
